Feature/ex 110 use camera and mic hook
jellyfish-dev/react-client-sdk pull request #39
Opened 2023-08-30 11:52 UTC by kamil-stasiak

2023-08-30 11:57 UTC, kamil-stasiak commented on examples/readme.md
> +// todo add description
Fix toto

2023-08-30 11:57 UTC, kamil-stasiak commented on examples/use-camera-and-microphone-example/README.md
> +# React + TypeScript + Vite
Fix readme

2023-08-30 11:57 UTC, kamil-stasiak commented on examples/use-camera-and-microphone-example/public/vite.svg
Remove

2023-08-30 11:57 UTC, kamil-stasiak commented on examples/use-camera-and-microphone-example/src/App.tsx
> +// Jeżeli zaczniesz streamować urządzenia bardzo szybko to wybucha.
Report an error

2023-08-30 11:57 UTC, kamil-stasiak commented on examples/use-camera-and-microphone-example/src/App.tsx
> +    },
uncomment

2023-08-30 11:57 UTC, kamil-stasiak commented on src/create.tsx
> +  //  przesyłać tracki zaraz po dołączeniu
Report an error and remove this coment

2023-08-30 13:08 UTC, Crackhoff commented
When I connect and stop streaming either audio or video sometimes whole room crashes

2023-08-30 14:18 UTC, Crackhoff requested changes
I love the hook itself, but I have some questions about the example

2023-08-30 15:44 UTC, kamil-stasiak commented on examples/use-camera-and-microphone-example/src/AudioVisualizer.tsx
> +      <canvas ref={canvasRef} width={200} height={100}/>
Fixed. Now the canvas width matches the width of its parent container

2023-08-30 15:44 UTC, kamil-stasiak commented on examples/use-camera-and-microphone-example/src/App.tsx
> +import "./App.css";
Removed

2023-08-30 15:45 UTC, kamil-stasiak commented on examples/use-camera-and-microphone-example/src/App.css
Removed

2023-08-30 15:47 UTC, kamil-stasiak commented on examples/use-camera-and-microphone-example/src/App.tsx
> +            Streaming
Fixed. Now it looks like this:

2023-08-30 15:50 UTC, kamil-stasiak commented
> Bug: When I connect and stop streaming either audio or video sometimes whole room crashes

I think it's a bug in Jellyfish, and I believe it's already fixed. Please check the latest commit on the 'main' branch

> When I have auto streaming on and I connect to the server, on dashboard I see two video tracks. What's the cause? If one sends both audio and video, why there is another? If they're both video-only, what happens with audio and why there are two of them?

And I think it'a a bug in `jellyfish-dashboard`. We need to address it in a separate task

2023-08-31 13:13 UTC, Crackhoff approved these changes
All good!

2023-08-31 13:13 UTC, Crackhoff commented on readme.md
> +  You u can use [dashboard](https://github.com/jellyfish-dev/jellyfish-dashboard) to create room and peer token.
typo, "u"

2023-08-31 14:09 UTC, merged